apiVersion: v1
kind: Service
metadata:
  name: dtr-rethinkdb-proxy
  labels:
    app: rethinkdb-proxy
    chart: rethinkdb-0.0.3
    heritage: Tiller
    release: dtr
  annotations:
spec:
  type: ClusterIP
  clusterIP: ""
  ports:
    - port: 28015
      targetPort: driver
  selector:
    app: rethinkdb-proxy
    release: dtr
