apiVersion: v1
kind: Service
metadata:
  name: "dtr-rethinkdb-admin"
  labels:
    app: "rethinkdb-admin"
    chart: "rethinkdb-0.0.3"
    heritage: "Tiller"
    release: "dtr"
spec:
  clusterIP: None
  ports:
    - port: 8080
      targetPort: admin
  selector:
    app: "rethinkdb-proxy"
    release: "dtr"
